image: node:alpine

pages:
  script:
    - yarn config set cache-folder .yarn
    - yarn global add node-gyp
    - yarn install
    - yarn add gatsby-cli
    - mkdir -p ./public/.well-known/acme-challenge/58gNzwSpybhMrNMgezb9BBPuHqvuaCzWAtXkqIBFUPo
    - cp .well-known/acme-challenge/58gNzwSpybhMrNMgezb9BBPuHqvuaCzWAtXkqIBFUPo/index.html ./public/.well-known/acme-challenge/58gNzwSpybhMrNMgezb9BBPuHqvuaCzWAtXkqIBFUPo/index.html
    - node_modules/.bin/gatsby build --prefix-paths
  artifacts:
    paths:
      - public
  cache:
    paths:
      - node_modules
      - .yarn
  only:
    - master
