image: node:6.10.0

stages:
  - test
  - install
  - copy
  - deploy

install:
  stage: install
  script:
  - npm install
  - npm install gatsby-cli

copy:
  stage: copy
  script:
    - mkdir -p ./public/.well-known/acme-challenge/58gNzwSpybhMrNMgezb9BBPuHqvuaCzWAtXkqIBFUPo
    - cp .well-known/acme-challenge/58gNzwSpybhMrNMgezb9BBPuHqvuaCzWAtXkqIBFUPo/index.html ./public/.well-known/acme-challenge/58gNzwSpybhMrNMgezb9BBPuHqvuaCzWAtXkqIBFUPo/index.html


pages:
  stage: deploy
  script:
    - node_modules/.bin/gatsby build --prefix-paths
  artifacts:
    paths:
      - public
  cache:
    paths:
      - node_modules
  only:
    - master
    
test:
  stage: test
  script: npm test
  artifacts:
    paths:
      - test
  except:
    - master
